server:
  port: 9090
  servlet:
    context-path: /expenses-control

spring:
  application:
    name: expense-service-api
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

application:
  default-time-zone: UTC
